FROM gocd/gocd-server

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y install wget

RUN wget --quiet https://github.com/tomzo/gocd-yaml-config-plugin/releases/download/0.4.0/yaml-config-plugin-0.4.0.jar \
-P /var/lib/go-server/plugins/external/

# cleanup
RUN apt-get -y autoremove
RUN rm -rf /var/lib/apt/lists/*
