FROM gocd/gocd-agent-ubuntu-16.04:v17.3.0

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y --force-yes luarocks ca-certificates-java
RUN update-ca-certificates -f
RUN luarocks install busted
RUN lua -v

# cleanup
RUN apt-get -y autoremove
RUN rm -rf /var/lib/apt/lists/*
