FROM gocd/gocd-server:v18.7.0

COPY ./server_home/config/cruise-config.xml /godata/config/cruise-config.xml

COPY ./server_home/config/cruise-config.xml /godata/config/cruise-config.xml2

RUN chown -R go:go /godata
