FROM gocd/gocd-server:v17.9.0

COPY ./server_home/config/cruise-config.xml /go-working-dir/config/cruise-config.xml

COPY ./server_home/config/cruise-config.xml /go-working-dir/config/cruise-config.xml2

RUN chown -R go:go /go-working-dir /godata
