FROM debian

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y install python-pip

RUN pip install requests

# cleanup
RUN apt-get -y autoremove
RUN rm -rf /var/lib/apt/lists/*

COPY setup_pipelines.py /

CMD python /setup_pipelines.py
